### ISSUE TITLE
composer installation uses SSH instead of HTTPS

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt-core#45]
I figured out that installing this package via Composer without using a registered SSH key will not work and you'll need to enter a Github Auth Token which can't be done in a lot of terminal emulators because copy/paste is disabled.

Maybe it's just better to use HTTPS so you don't need a Github account to use this.

Currently it wants to install from `git@github.com:bleech/wp-starter-plugin.git`

**Comment by bdbch** [comment]
@domtra @Qakulukiam any update?

**Comment by Qakulukiam** [comment]
@bdbch thank you for the issue, @domtra could you please evaluate this?

**Comment by Qakulukiam** [comment]
This was caused by the flynt-cli, resolved in this PR https://github.com/flyntwp/flynt-cli/pull/77 and released in version [v0.2.0](https://github.com/flyntwp/flynt-cli/releases/tag/v0.2.0)
